"""Type stubs for eo_processor"""

from typing import Literal
import numpy as np
from numpy.typing import NDArray

__version__: Literal["0.3.0"]

def normalized_difference(
    a: NDArray[np.float64], b: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def ndvi(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi(
    green: NDArray[np.float64], nir: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def savi(
    nir: NDArray[np.float64], red: NDArray[np.float64], L: float = ...
) -> NDArray[np.float64]: ...
def nbr(
    nir: NDArray[np.float64], swir2: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def ndmi(
    nir: NDArray[np.float64], swir1: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def nbr2(
    swir1: NDArray[np.float64], swir2: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def gci(
    nir: NDArray[np.float64], green: NDArray[np.float64]
) -> NDArray[np.float64]: ...
def enhanced_vegetation_index(
    nir: NDArray[np.float64], red: NDArray[np.float64], blue: NDArray[np.float64]
) -> NDArray[np.float64]: ...
evi = enhanced_vegetation_index

def median(arr: NDArray[np.float64], skip_na: bool = ...) -> NDArray[np.float64]: ...
def composite(arr: NDArray[np.float64], method: str = ..., **kwargs) -> NDArray[np.float64]: ...
def temporal_mean(arr: NDArray[np.float64], skip_na: bool = ...) -> NDArray[np.float64]: ...
def temporal_std(arr: NDArray[np.float64], skip_na: bool = ...) -> NDArray[np.float64]: ...

def euclidean_distance(points_a: NDArray[np.float64], points_b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def manhattan_distance(points_a: NDArray[np.float64], points_b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def chebyshev_distance(points_a: NDArray[np.float64], points_b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def minkowski_distance(points_a: NDArray[np.float64], points_b: NDArray[np.float64], p: float) -> NDArray[np.float64]: ...
# Raises ValueError if p < 1.0
