"""Type stubs for eo_processor"""

import numpy as np
from numpy.typing import NDArray

__version__: str

def normalized_difference_1d(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def normalized_difference_2d(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def normalized_difference_3d(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi_1d(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi_2d(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi_3d(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi_1d(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi_2d(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...
def enhanced_vegetation_index_1d(
    nir: NDArray[np.float64],
    red: NDArray[np.float64],
    blue: NDArray[np.float64],
    g: float = 2.5,
    l: float = 1.0,
    c1: float = 6.0,
    c2: float = 7.5,
) -> NDArray[np.float64]: ...
def enhanced_vegetation_index_2d(
    nir: NDArray[np.float64],
    red: NDArray[np.float64],
    blue: NDArray[np.float64],
    g: float = 2.5,
    l: float = 1.0,
    c1: float = 6.0,
    c2: float = 7.5,
) -> NDArray[np.float64]: ...

def normalized_difference(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...
def enhanced_vegetation_index(
    nir: NDArray[np.float64],
    red: NDArray[np.float64],
    blue: NDArray[np.float64],
    g: float = 2.5,
    l: float = 1.0,
    c1: float = 6.0,
    c2: float = 7.5,
) -> NDArray[np.float64]: ...
