"""Type stubs for eo_processor"""

import numpy as np
from numpy.typing import NDArray

__version__: str

def normalized_difference_1d(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def normalized_difference_2d(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi_1d(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi_2d(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi_1d(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi_2d(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...

def normalized_difference(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndvi(nir: NDArray[np.float64], red: NDArray[np.float64]) -> NDArray[np.float64]: ...
def ndwi(green: NDArray[np.float64], nir: NDArray[np.float64]) -> NDArray[np.float64]: ...
